language: java
install:
 - mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V -pl core,extensions,extensions/db2,extensions/postgres
script:
 - mvn test -Dmaven.javadoc.skip=true -B -V -pl core,extensions,extensions/db2